### PR TITLE
Added sirlisko portfolio

### PR DESCRIPTION
**Pull request by sirLisko**
Added my website/portfolio, https://sirlisko.com.

Here you can see a couple of screenshots from different areas of the website:

**Home**
Screenshot 2019-10-03 at 22 09 36

**Projects**
Screenshot 2019-09-17 at 15 23 40

**CV**
Screenshot 2019-09-17 at 15 23 55

### CODE REVIEW

**Comment by evanplaice** [comment]
@sirLisko FYI, in the future when you submit a PR to a project; try to keep the changes as small as possible. Changes like whitespace fixes and changing the order of code/modules makes it more difficult for maintainers to merge in your changes.

If you follow this rule, you'll find project maintainers much more receptive to your PRs.

**Comment by eclectic-coding** [comment]
Evan
Maybe we need to consider adding a CONTRIBUTION guide.

**Comment by evanplaice** [comment]
@eclectic-coding Good point, it wouldn't hurt to outline some general guidelines for contributing to Open Source.

**Comment by sirLisko** [comment]
@evanplaice sorry about that 😅 

Otherwise, an `.editorconfig` would be ideal, even if I can see the point of keeping the repo as barebone as possible.

**Comment by evanplaice** [comment]
@sirLisko No worries. It's just a nit (ie nitpick) followed up with some useful advice.

It seems petty but some maintainers will just ignore commits with extra/unnecessary changes because they don't want to deal with the potential merge conflicts those changes may create. Speaking from personal experience, it can be very frustrating to put work into a PR only to have it be ignored with zero feedback about why.

TBH, it doesn't matter if your PR had been perfect. Every single remaining PR has merge conflicts because a previously merged PR had reordered and prefixed all the names with `*`.

**Pull request merged**
